### ISSUE TITLE
No ansible playbook to insert the new provider into arbitrary mangeiq

### ISSUE THREAD

**Issue by yaacov** [container-mgmt/ocp-ansible-jenkins#13]
Currently we are working on creating and running a playbook for inserting the new provider into a Podified Mangeiq.

In Development we need to run this playbook by hand on our dev manageiq.

**Comment by elad661** [comment]
My podified branch adds the Openshift provider automatically to ManageIQ, but what @yaacov wants is a simple command to add the provider to a local dev installation.

**Comment by elad661** [comment]
Addressed in PR #17
