### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by coolpalani** [container-mgmt/ocp-ansible-jenkins#32]
How do I use this repo for deploy Openshift Container Platform.
If you share instructions or pre recorded video, it would be great.

**Comment by elad661** [comment]
We use this project internally to deploy OCP environments for testing. I wouldn't recommend using it for real-world scenarios :)

If you want to deploy OpenShift Origin, you should take a look at [openshift-ansible](https://github.com/openshift/openshift-ansible), which is the standard way of installing Origin. This is what we use too, oc-ansible-jenkins is just a bunch of utility around that.

The code we have in ocp-ansible-jenkins can generate ansible inventory files (take a look at `create_inventory.py`) for openshift-ansible but I don't know if it'll be of any use to you.

**Comment by coolpalani** [comment]
I though it may useful.
Better I suggest you, such a stuff make it as private repository.
so that people won't get confusion or expectations.
