### ISSUE TITLE
Needed changes

### ISSUE THREAD

**Issue by moolitayer** [container-mgmt/ocp-ansible-jenkins#4]
- [x] Support proper AAA (users should only be allowed to run jobs, use internal LDAP ?)
- [ ] Add etcd nodes
- [ ] Additional variables[1]
- [x] Extract LDAP details to variable https://github.com/moolitayer/ocp-ansible-jenkins/pull/5
- [x] Support openshift_install_examples option ~~https://github.com/moolitayer/ocp-ansible-jenkins/pull/6~~ https://github.com/moolitayer/ocp-ansible-jenkins/pull/5
- [x] Add a new openshift_docker_[additional/insecure]_registries [new-job](http://cm-jenkins.usersys.redhat.com:8080/job/ocp-ansible-jenkins-copy)
- [x] Support plugins (urls of bash script/s to pull and execute on master, show output) #9 
- [x] Output cluster service account (using plugin?) #9

[1]
openshift_master_cluster_hostname=internal.api.certtest.openshift.com
openshift_master_cluster_public_hostname=api.certtest.openshift.com
openshift_master_public_api_url=https://api.certtest.openshift.com
openshift_master_public_console_url=https://console.certtest.openshift.com/console
osm_custom_cors_origins=[u'console.certtest.openshift.com', u'api.certtest.openshift.com']

**Comment by moolitayer** [comment]
cc @simon3z @zgalor

**Comment by elad661** [comment]
This issue is obsolete as all the features on the list have already been implemented
